djsite/djsite/urls.py
from django.views.static import serve
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib import admin
from rest_framework import routers

from app.views import home,department,user,partner,admin,account,task,work,chart,file,vue,register,team

router = routers.DefaultRouter()
router.register(r'team',team.TeamViewSet)

urlpatterns = [
    # rest_framework api
    path('api/',include(router.urls)),

    # 配置 media 用户数据目录
    re_path(r'^media/(?P<path>.*)$', serve, {'ducument_root': settings.MEDIA_ROOT}, name='media'),

    # 首页
    path('',home.index),
    
    # 用户注册
    path('register/',register.register),

    # 部门管理
    path('department/list/',department.department_list),
    path('department/add/',department.department_add),
    path('department/delete/',department.department_delete),
    path('department/<int:nid>/edit/',department.department_edit),
    path('department/multi/',department.department_multi),

    #用户管理
    path('user/list/',user.user_list),
    path('user/add/',user.user_add),
    path('user/<int:nid>/delete/',user.user_delete),
    path('user/<int:nid>/edit/',user.user_edit),
    path('user/model/form/add/',user.user_model_form_add),
    
    # 客商管理
    path('partner/list/',partner.partner_list),
    path('partner/add/',partner.partner_add),
    path('partner/<int:nid>/delete/',partner.partner_delete),
    path('partner/<int:nid>/edit/',partner.partner_edit),
    
    # 管理员
    path('admin/list/',admin.admin_list),
    path('admin/add/',admin.admin_add),
    path('admin/<int:nid>/delete/',admin.admin_delete),
    path('admin/<int:nid>/edit/',admin.admin_edit),
    path('admin/<int:nid>/reset/',admin.admin_reset),
    
    # 登录/注销
    path('login/',account.login),
    path('logout/',account.logout),
    path('image/code/',account.image_code),
    
    # 任务管理
    path('task/list/',task.task_list),
    path('task/ajax/',task.task_ajax),
    path('task/add/',task.task_add),

    # 工单管理
    path('work/list/',work.work_order_list),
    path('work/add/',work.work_order_add),
    path('work/delete/',work.work_order_delete),
    path('work/edit/',work.work_order_edit),
    path('work/edit/save/',work.work_order_edit_save),
    path('work/cancel/<int:pk>',work.work_order_cancel,name="work_order_cancel"),    # 撤单

    # 图表
    path('chart/list/',chart.chart_list),
    path('chart/bar/',chart.chart_bar),

    # 文件管理
    path('file/upload/list/',file.upload_list),
    path('file/upload/form/',file.upload_form),
    path('file/upload/modelform/',file.upload_modelform),
    path('file/upload/employee/',file.upload_employee),

    # vue
    path('vue/test01/',vue.vue_test01),

]

djsite/app/models.py
from time import timezone
from django.db import models

class ActiveBaseModel(models.Model):
    """ 状态 """
    active = models.SmallIntegerField(
        verbose_name="状态",
        default=1,
        choices=(
            (1,"激活"),
            (2,"删除")
        )
    )
    class Meta:
        abstract = True

class MeansBaseModel(models.Model):
    """ 生产资料/资源分类"""
    
    type = models.SmallIntegerField(
        verbose_name="类型",
        default=1,
        choices=(
            (1,"物料"),
            (2,"工装"),
            (3,"设备"),
            (4,"人员"),
            (5,"其他")
        )
    )

class Department(models.Model):
    """ 部门 """
    title = models.CharField(verbose_name='部门',max_length=32)
    def __str__(self):
        return self.title
    
class User(models.Model):
    """ 用户 """
    name = models.CharField(verbose_name='姓名',max_length=16)
    password = models.CharField(verbose_name='密码',max_length=64)
    age = models.IntegerField(verbose_name='年龄',default=18)
    balance = models.DecimalField(verbose_name='账户余额',max_digits=10,decimal_places=2, default=0)
    create_time = models.DateField(verbose_name='建档时间')
    gender_choices = ((1,"男"),(2,"女"),)
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices,default=2)
    # # 部门级联删除
    depart = models.ForeignKey(verbose_name='部门',to="Department",to_field="id",on_delete=models.CASCADE)
    # # 部门级联置空
    # depart = models.ForeignKey(verbose_name='部门',to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    def __str__(self):
        return self.name
    
class UserInfo(models.Model):
    """ 用户信息  """
    name = models.CharField(verbose_name='姓名',max_length=16)
    password = models.CharField(verbose_name='密码',max_length=64)
    age = models.IntegerField(verbose_name='年龄',default=18)
    balance = models.DecimalField(verbose_name='账户余额',max_digits=10,decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name='建档时间')
    gender_choices = ((1,"男"),(2,"女"),)
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices,default=2)
    # # 部门级联删除
    #depart = models.ForeignKey(to="Department",to_field="id",on_delete=models.CASCADE)
    # # 部门级联置空
    department = models.ForeignKey(verbose_name='部门',to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=20)
    def __str__(self):
        return self.name

class Employee(models.Model):
    """ 人员 """
    name = models.CharField(verbose_name='姓名',max_length=16)
    age = models.IntegerField(verbose_name='年龄',default=18)
    gender_choices = ((1,"男"),(2,"女"),)
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices,default=1)
    img = models.FileField(verbose_name='图片',max_length=128,default=None,upload_to='employee/')
    photo = models.FileField(verbose_name='头像',max_length=128,default=None,upload_to='employee/')
    create_time = models.DateField(verbose_name='建档时间',auto_now_add=True)
    # # 部门级联删除
    #depart = models.ForeignKey(to="Department",to_field="id",on_delete=models.CASCADE)
    # # 部门级联置空
    department = models.ForeignKey(verbose_name='部门',to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=20)

class Partner(models.Model):
    """ 客商 business partner（客户&供应商）customers and merchants """
    number = models.CharField(verbose_name='客户代码',max_length=32,unique=True)
    name = models.CharField(verbose_name='客户名称',max_length=32,unique=True)
    short_name = models.CharField(verbose_name='客户简称',max_length=16,unique=True)
    telephone_number = models.CharField(verbose_name='电话号码',max_length=32)
    category_choices = ((1,"客户"),(2,"供应商"))
    category = models.SmallIntegerField(verbose_name='类别',choices=category_choices,default=1)
    region_choices = (
        (1,"华北"),(2,"东北"),(3,"华东"),(4,"华中"),(5,"华南"),(6,"西南"),(7,"西北"),(8,"港澳台")
        )
    region = models.SmallIntegerField(verbose_name='区域',choices=region_choices,default=1)
    status_choices = ((1,"启用"),(2,"停用"))
    status = models.SmallIntegerField(verbose_name='状态',choices=status_choices,default=1)
    def __str__(self):
        return self.name

class Material(models.Model):
    """ 物料 """
    number = models.CharField(verbose_name='物料编码',max_length=32,unique=True)
    code = models.CharField(verbose_name='物料代码',max_length=32)
    name = models.CharField(verbose_name='物料名称',max_length=32)
    uom = models.ForeignKey(verbose_name='计量单位',to="UomGroup",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    def __str__(self):
        return self.number
    
class BasicUom(models.Model):
    """ 基本计量单位 """
    code = models.CharField(verbose_name='基本计量单位代码',max_length=32,unique=True)
    name  = models.CharField(verbose_name='基本计量单位',max_length=32)

class UomGroup(models.Model):
    """ 计量单位组 """
    uom_group_code = models.CharField(verbose_name='计量单位组代码',max_length=32,unique=True)
    name  = models.CharField(verbose_name='计量单位组',max_length=32,unique=True)
    level_choices = ((1,"主计量"),(2,"辅助计量"),)
    level = models.SmallIntegerField(verbose_name='计量类别',choices=level_choices,default=1)
    conversion_rate = models.DecimalField(verbose_name='换算率',max_digits=10,decimal_places=2, default=1)
    basic_uom = models.ForeignKey(verbose_name='计量单位',to="BasicUom",to_field="id",on_delete=models.CASCADE) 
    
class ProductOrder(models.Model):
    """# 生产订单 """
    number = models.CharField(verbose_name='生产订单号',max_length=32,unique=True)
    create_date = models.DateField(verbose_name='单据日期')
    expect_date = models.DateField(verbose_name='计划完成日期')
    department = models.ForeignKey(verbose_name='生产部门',to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    customer = models.ForeignKey(verbose_name='客户',to="Partner",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    
class ProductOrders(models.Model):
    """# 生产订单明细   """
    number = models.CharField(verbose_name='生产订单行号',max_length=16,unique=True)
    expect_date = models.DateField(verbose_name='计划完成日期')
    production_order = models.ForeignKey(verbose_name='生产订单号',to="ProductOrder",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)  
    quantity = models.DecimalField(verbose_name='数量',max_digits=10,decimal_places=2, default=0)

class Admin(models.Model):
    """# 管理员 """
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)
    def __str__(self):
            return self.username

class Task(models.Model):
    """ 任务 """
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题",max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人",to="Admin",to_field="id", on_delete=models.CASCADE)

class WorkOrder(models.Model):
    """# 派工单 WorkOrder """
    number = models.CharField(verbose_name='工单号',unique=True,max_length=64)
    create_date = models.DateField(verbose_name='单据日期')
    planned_start_date = models.DateField(verbose_name='计划开始日期')
    planned_completion_date = models.DateField(verbose_name='计划完工日期')
    department = models.ForeignKey(verbose_name='生产部门',to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    partner = models.ForeignKey(verbose_name='客户',to="Partner",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    material = models.ForeignKey(verbose_name='产品',to="Material",to_field="id",null=True,blank=True,on_delete=models.SET_NULL,default=None)
    quantity = models.DecimalField(verbose_name='数量',max_digits=10,decimal_places=2, default=1)
    admin = models.ForeignKey(verbose_name='操作员',to="Admin",to_field="id",on_delete=models.CASCADE)
    status_choices = (
        (1, "开立"),
        (2, "开启"),
        (3, "执行"),
        (4, "停滞"),
        (5, "完工"),
        (6, "关闭"),
        (7, "撤销")
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices,default=1)

class WorkFrom(models.Model):
    """ 报工单/转序单  """
    pass

class ProcessTransferForm(models.Model):
    """ 工序转移单 """
    pass

class Equitpment(models.Model):
    """ 设备 """
    pass

class ProcessRoute(models.Model):
    """ 工艺路线 """
    pass

class Workmanship(models.Model):
    """ 标准工艺  """
    pass

class MeansProduction(models.Model):
    """ 生产资料 """

class WagesQtuota(models.Model):
    """ 计件工资定额  """
    pass

class Wages(models.Model):
    """ 计件工资 """
    pass

class Team(models.Model):
    """ 班组 """
    code = models.CharField(verbose_name='班组代码',max_length=16)
    title = models.CharField(verbose_name='班组名称',max_length=32,default=None)
    content = models.TextField(verbose_name='班组说明',default=None)
    posttime = models.DateTimeField(verbose_name='记录时间',auto_now = True)

    class Meta:
        db_table = "erp_team"

class WorkCenter(models.Model):
    """ 工作中心 """
    pass

class ProductInspectionForm(models.Model):
    """ 检验单 """
    pass

class InspectionSchema(models.Model):
    """ 检验方案 """
    pass

class InspectionItem(models.Model):
    """ 检验项目 """
    pass

class ProductionScheduling(models.Model):
    """ 生产排程 """
    pass

class AttendanceRecord(models.Model):
    """" 考勤表 """
    pass

djsite/app/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}

<div style="margin-bottom:10px;" class="clearfix">
    <a class="btn btn-primary" href="/admin/add/">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增管理员
    </a>
    <div style="float: right">
        <form method="get" action="">
            <div class="input-group">            
                <input type="text" name="q" class="form-control" 
                        placeholder="搜索...(管理员)" value="{{ search_data }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </span>            
            </div>
        </form>
    </div>
</div>
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 管理员列表
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>帐号</th>
                    <th>密码</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.username }}</td>
                    <td>{{ obj.password}}</td>
                    <td>
                        <a href="/admin/{{ obj.id }}/reset">重置密码</a>
                    </td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/admin/{{ obj.id }}/edit/">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 编辑
                        </a>
                        <a class="btn btn-danger btn-xs" href="/admin/{{ obj.id }}/delete/">
                            <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> 删除
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <nav aria-label="Page navigation">
            <ul class="pagination" style="float:left;">
                {{ page_string }}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

djsite/app/templates/change.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" 
        href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <!--<div class="container">-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form method="post" >
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    <!--</div>-->
{% endblock %}

{% block js %}
    <script 
        src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}">
    </script>
    <script 
        src="{% static 'plugins/bootstrap-datepicker/js/locales/bootstrap-datepicker.zh-CN.js' %}">
    </script>

    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            });
        })
    </script>
{% endblock %}

djsite/app/templates/department_add.html
{% extends 'layout.html' %}

{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>新增部门</h3>
        </div>
        <div class="panel-body">
            <form method="post" action="#" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="">标题</label>
                    <input type="text" class="form-control" placeholder="标题" name="title">
                </div>
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>

{% endblock %}

djsite/app/templates/department_list.html
{% extends 'layout.html' %}

{% block content %}
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"> 上传文件</span>
      </div>
      <div class="panel-body">
        <form method="post" enctype="multipart/form-data" action="/department/multi/">
          {% csrf_token %}
          <div class="form-group">
            <label for="exampleInputFile">选择文件</label>
            <input type="file" id="exampleInputFile" name="xlsx">
            <p class="help-block">请选择本地文件.</p>
          </div>
          <input type="submit" class="btn btn-info btn-sm" value="上传" >
        </form>
      </div>
      
    </div>

    <div style="margin-bottom: 10px;">
      <a class="btn btn-primary" href="/department/add/">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增部门
      </a>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 部门列表
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>ID</th>
            <th>部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          {% for obj in queryset %}
            <tr>
              <th scope="row">{{ obj.id }}</th>
              <td>{{ obj.title }}</td>
              <td>
                <a class="btn btn-primary btn-xs" href="/department/{{ obj.id }}/edit/">
                  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 编辑
                </a>
                <a class="btn btn-danger btn-xs" href="/department/delete/?nid={{ obj.id }}">
                  <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> 删除
                </a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

djsite/app/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <h3>{{ msg }}</h3>
{% endblock %}

djsite/app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <h1>首页</h1>
{% endblock %}

djsite/app/templates/partner_add.html
{% extends 'layout.html' %}
{% block content %}
    <!--<div class="container">-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新增客商</h3>
            </div>
            <div class="panel-body">
                <form method="post" >
                    {% csrf_token %}
                    
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    <!--</div>-->
{% endblock %}

djsite/app/templates/partner_list.html
{% extends 'layout.html' %}

{% block content %}

<div style="margin-bottom:10px;" class="clearfix">
    <a class="btn btn-primary" href="/partner/add/">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增客商
    </a>
    <div style="float: right">
        <form method="get" action="">
            <div class="input-group">            
                <input type="text" name="q" class="form-control" 
                        placeholder="搜索...(客商名称)" value="{{ search_data }}">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                </span>            
            </div>
        </form>
    </div>
</div>
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 客商列表
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>客商代码</th>
                    <th>客商名称</th>
                    <th>客商简称</th>
                    <th>客商类别</th>
                    <th>区域</th>
                    <th>电话号码</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.number }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.short_name }}</td>
                    <td>{{ obj.get_category_display }}</td>
                    <td>{{ obj.get_region_display }}</td>
                    <td>{{ obj.telephone_number }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/partner/{{ obj.id }}/edit/">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 编辑
                        </a>
                        <a class="btn btn-danger btn-xs" href="/partner/{{ obj.id }}/delete/">
                            <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> 删除
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <nav aria-label="Page navigation">
            <ul class="pagination" style="float:left;">
                {{ page_string }}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}

djsite/app/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div>
                <div class="panel-heading">任务列表</div>
                <div class="panel-body">

                    <form  id="formAdd" novalidate>
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative; margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg"  style="color: red; position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="col-xs-12">
                            <button id="btnAdd" type="button" class="btn btn-primary">提交</button>
                        </div>
                    </form>

                    <hr/>

                    <table class="table table-bordered">
                        <head>
                            <tr>
                                <th>ID</th>
                                <th>标题</th>
                                <th>级别</th>
                                <th>详细信息</th>
                                <th>负责人</th>
                                <th>操作</th>
                            </tr>
                        </head>
                        <tbody>
                            {% for obj in queryset %}
                                <tr>
                                    <td>{{ obj.id }}</td>
                                    <td>{{ obj.title }}</td>
                                    <td>{{ obj.get_level_display }}</td>
                                    <td>{{ obj.detail }}</td>
                                    <td>{{ obj.user }}</td>
                                    <td>
                                        <a class="btn btn-primary btn-xs" href="#">编辑</a>
                                        <a class="btn btn-primary btn-xs" href="#">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                    <ul class="pagination">
                        {{ page_string }}
                    </ul>

                </div>
            </div>
        </div>

        <div style="height: 500px;"></div>

        <hr/>
        <div>
            <h1>Ajaxs示例</h1>
            <h3>示例1</h3>
            <input type="button" id="btn1" class="btn btn-primary" value="点击" />

            <h3>示例2</h3>
            <input type="text" id="txtUser" placeholder="姓名" />
            <input type="text" id="txtAge" placeholder="年龄" />
            <input type="button" id="btn2" class="btn btn-primary" value="点击" />

            <h3>示例3</h3>
            <form id="form3">
                <input type="text" name="user" placeholder="姓名" />
                <input type="text" name="age" placeholder="年龄" />
                <input type="text" name="email" placeholder="邮箱" />
            </form>
            <input type="button" id="btn3" class="btn btn-primary" value="点击" />
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        // 页面框架加载后自动执行
        $(function () {
            bindBtnAddEvent();
            bindBtn1Event();
            bindBtn2Event();
            bindBtn3Event();
        }) 

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if(res.status){
                            alert("任务添加成功");
                            location.reload();
                        }else {
                            $.each(res.error,function (name,data){
                                //console.log(name,data);
                                $("#id_" + name).next().text(data[0])
                            })
                        }
                    }
                })
            })
        }

        function bindBtn1Event() {
            $("#btn1").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type: "post",
                    data:{
                        n1: 123,
                        n2: 456
                    },
                    datatype: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            })
        }

        function bindBtn2Event() {
            $("#btn2").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type: "post",
                    data:{
                        name: $("#txtUser").val(),
                        age: $("#txtAge").val()
                    },
                    datatype: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            }) 
        }

        function bindBtn3Event() {
            $("#btn3").click(function () {
                $.ajax({
                    url: '/task/ajax/',
                    type: "post",
                    data: $("#form3").serialize(),
                    datatype: "JSON",
                    success: function (res) {
                        console.log(res);
                        console.log(res.status);
                        console.log(res.data);
                    }
                })
            }) 
        }
    </script>
{% endblock %}

djsite/app/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}

<div style="margin-bottom:10px;">
    <a class="btn btn-primary" href="/user/model/form/add/">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 新增用户
    </a>
</div>
<div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 用户列表
        </div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>性别</th>
                    <th>年龄</th>
                    <th>余额</th>
                    <th>部门</th>
                    <th>日期</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in queryset %}
                <tr>
                    <td>{{ obj.id }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.password }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.balance }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>{{ obj.create_time|date:"Y-m-d" }}</td>
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 编辑
                        </a>
                        <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/delete/">
                            <span class="glyphicon glyphicon-erase" aria-hidden="true"></span> 删除
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <nav aria-label="Page navigation">
            <ul class="pagination" style="float:left;">
                {{ page_string }}
            </ul>
        </nav>
    </div>
</div>
{% endblock %}